stages:
- compile
- build
- test

variables:
  RELEASE: "30"
  POSTGRES_DB: "nice_marmot"
  POSTGRES_USER: "runner"
  POSTGRES_PASSWORD: "password"

compile_job_9.6:
  variables:
    PG_VER: "9.6"
  image:
    name: registry.gitlab.com/thehyve/ci_images/of_pg_dev:${PG_VER}
  stage: compile
  artifacts:
    name: "$CI_JOB_NAME"
    when: on_success
    expire_in: 1h
    paths:
    - pg_bitcount*
  script:
  - make

compile_job_10:
  variables:
    PG_VER: "10"
  image:
    name: registry.gitlab.com/thehyve/ci_images/of_pg_dev:${PG_VER}
  stage: compile
  artifacts:
    name: "$CI_JOB_NAME"
    when: on_success
    expire_in: 1h
    paths:
    - pg_bitcount*
  script:
  - make

compile_job_11:
  variables:
    PG_VER: "11"
  image:
    name: registry.gitlab.com/thehyve/ci_images/of_pg_dev:${PG_VER}
  stage: compile
  artifacts:
    name: "$CI_JOB_NAME"
    when: on_success
    expire_in: 1h
    paths:
    - pg_bitcount*
  script:
  - make

build_job_9.6:
  dependencies:
  - compile_job_9.6
  variables:
    PG_VER: "9.6"
  image: registry.gitlab.com/containertools/containertools:${RELEASE}
  stage: build
  script:
  - ./build.sh

build_job_10:
  dependencies:
  - compile_job_10
  variables:
    PG_VER: "10"
  image: registry.gitlab.com/containertools/containertools:${RELEASE}
  stage: build
  script:
  - ./build.sh

build_job_11:
  dependencies:
  - compile_job_11
  variables:
    PG_VER: "11"
  image: registry.gitlab.com/containertools/containertools:${RELEASE}
  stage: build
  script:
  - ./build.sh

test_job_9.6:
  dependencies:
  - build_job_9.6
  stage: test
  variables:
    PG_VER: "9.6"
  services:
  - registry.gitlab.com/thehyve/pg_bitcount:${PG_VER}
  image:
    name: registry.gitlab.com/thehyve/ci_images/of_pg_dev:${PG_VER}
  script:
  - ./test.sh

test_job_10:
  dependencies:
  - build_job_10
  stage: test
  variables:
    PG_VER: "10"
  services:
  - registry.gitlab.com/thehyve/pg_bitcount:${PG_VER}
  image:
    name: registry.gitlab.com/thehyve/ci_images/of_pg_dev:${PG_VER}
  script:
  - ./test.sh

test_job_11:
  dependencies:
  - build_job_11
  stage: test
  variables:
    PG_VER: "11"
  services:
  - registry.gitlab.com/thehyve/pg_bitcount:${PG_VER}
  image:
    name: registry.gitlab.com/thehyve/ci_images/of_pg_dev:${PG_VER}
  script:
  - ./test.sh
