env:
  global:
    secure: OjpbosRgm3h9onQ4/79RobuXWbpWjnvjgoqf0tOcm2LBZT/3SNyeRSwvtR8PlmRxTGKH1ssiUKClTUQlJYqJ9PDfvzwNqr1BK8VXlMjJZPJWnRtGH+R7IsgsQusC/KfEB0kRsqaiDrhPFpsGJWrGwV6s399Rav2MCSDvnLLDdGk+j/KXUrpvs5LGzUl0WokOPXUvaowowOLR18GnxGjO4ZhlgY5slZGzI6o4rSPu98EYG+EdZnQzql5cYS06KlRjH+x4ieV7EgQBEzXIlUGVbcgu4saywGK5tkO1ace15VoiamJ7nYOauryLCxvXc29TMp/B76/GbLM437fshw/PHRuUO3ZAILCMf56D/fgYm6NjhOVD26bhG59dqMlttRW4EjlHRcKak50KPMpIZPpETvfulN302yfhlIss2dYlMQejVsxYUTlxCJwKJUcHX+m6qEChRzGiEXMmmP/YTJishmfzsCdfnivYV+qsUastEwG8Oe6dv1MzNmCNtyWgbWUjtbuz+ANyTDc/ckGOfnBOzzFPF+X2SFPhlpFDf78Y5zIPH4LrVhtSp9fXpOd0zdEmwJmqEt7PzluiYxq/CZuYq5rAeru6juK8+jTpNndQeXOOKcEiyoH1Lm87szPsD9iZfwxG35mdyHv9EUUcfrq5zjZlhUJOTvQFlApeusaY2JA=

os:
  - linux
sudo: true
language: c

addons:
  postgresql: "9.6"
  apt:
    sources:
      - ubuntu-toolchain-r-test # for gcc-5 and gcc-7
    packages:
      - g++-5
      - gcc-5
      - g++-7
      - gcc-7
      - postgresql-server-dev-9.6

compiler:
  - gcc
  - gcc-5
  - gcc-7
  - clang

stage: compile

before_install:
  - ls -l /usr/lib/postgresql/
  - pushd /usr/lib/postgresql/; find -name "*pgxs*"; popd
  - make clean

install:
  - make

script:
  - make performance_tester
  - ./performance_tester

jobs:
  include:
    - stage: test
      env: POSTGRESQL_VERSION=9.6
      addons:
        postgresql: "9.6"
        apt:
          packages:
            - postgresql-server-dev-9.6
            - devscripts
            - build-essential
            - fakeroot
            - dh-make
      before_install:
        - sudo apt-get --yes remove postgresql-10 postgresql-client-10
      before_script:
        - sudo make install
      script:
        - make installcheck
      after_failure:
        - cat regression.diffs
      before_deploy:
        - ./package.sh
      deploy:
        provider: releases
        api_key:
          secure: ${RELEASE_KEY}
        file_glob: true
        file: build/postgresql-*-pg-bitcount_*.deb
        skip_cleanup: true
        on:
          repo: thehyve/pg_bitcount
          branch: master
          tags: true

    - stage: test
      env: POSTGRESQL_VERSION=10
      addons:
        postgresql: "10"
        apt:
          packages:
            - postgresql-server-dev-10
            - postgresql-10
            - postgresql-client-10
            - devscripts
            - build-essential
            - fakeroot
            - dh-make
      before_script:
        - sudo make install
      script:
        - make installcheck
      after_failure:
        - cat regression.diffs
      before_deploy:
        - ./package.sh
      deploy:
        provider: releases
        api_key:
          secure: ${RELEASE_KEY}
        file_glob: true
        file: build/postgresql-*-pg-bitcount_*.deb
        skip_cleanup: true
        on:
          repo: thehyve/pg_bitcount
          branch: master
          tags: true

    - stage: test
      env: POSTGRESQL_VERSION=11; PGPORT=5433
      addons:
        postgresql: "11"
        apt:
          packages:
            - devscripts
            - build-essential
            - fakeroot
            - dh-make
      before_install:
        - sudo apt-get --yes install postgresql-server-dev-11 postgresql-11 postgresql-client-11
        - sudo -u postgres psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;'
      before_script:
        - sudo make install
      script:
        - make installcheck
      after_failure:
        - cat regression.diffs
      before_deploy:
        - ./package.sh
      deploy:
        provider: releases
        api_key:
          secure: ${RELEASE_KEY}
        file_glob: true
        file: build/postgresql-*-pg-bitcount_*.deb
        skip_cleanup: true
        on:
          repo: thehyve/pg_bitcount
          branch: master
          tags: true

    - stage: test
      env: POSTGRESQL_VERSION=12; PGPORT=5433
      addons:
        postgresql: "12"
        apt:
          packages:
            - devscripts
            - build-essential
            - fakeroot
            - dh-make
      before_install:
        - sudo apt-get --yes install postgresql-server-dev-12 postgresql-12 postgresql-client-12
        - sudo -u postgres psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;'
      before_script:
        - sudo make install
      script:
        - make installcheck
      after_failure:
        - cat regression.diffs
      before_deploy:
        - ./package.sh
      deploy:
        provider: releases
        api_key:
          secure: ${RELEASE_KEY}
        file_glob: true
        file: build/postgresql-*-pg-bitcount_*.deb
        skip_cleanup: true
        on:
          repo: thehyve/pg_bitcount
          branch: master
          tags: true

    - stage: test
      env: POSTGRESQL_VERSION=13; PGPORT=5433
      addons:
        postgresql: "13"
        apt:
          packages:
            - devscripts
            - build-essential
            - fakeroot
            - dh-make
      before_install:
        - sudo apt-get --yes install postgresql-server-dev-13 postgresql-13 postgresql-client-13
        - sudo -u postgres psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;'
      before_script:
        - sudo make install
      script:
        - make installcheck
      after_failure:
        - cat regression.diffs
      before_deploy:
        - ./package.sh
      deploy:
        provider: releases
        api_key:
          secure: ${RELEASE_KEY}
        file_glob: true
        file: build/postgresql-*-pg-bitcount_*.deb
        skip_cleanup: true
        on:
          repo: thehyve/pg_bitcount
          branch: master
          tags: true
