os:
  - linux
sudo: true
language: c

addons:
  postgresql: "9.6"
  apt:
    sources:
      - ubuntu-toolchain-r-test # for gcc-5 and gcc-7
    packages:
      - g++-5
      - gcc-5
      - g++-7
      - gcc-7
      - postgresql-server-dev-9.6

compiler: 
  - gcc
  - gcc-5
  - gcc-7
  - clang

stage: compile

before_install:
  - ls -l /usr/lib/postgresql/
  - pushd /usr/lib/postgresql/; find -name "*pgxs*"; popd
  - make clean

install:
  - make
  - make performance_tester

script:
  - ./performance_tester

jobs:
  include:
    - stage: test
      env: POSTGRESQL_VERSION=9.4
      addons:
        postgresql: "9.4"
        apt:
          packages:
            - postgresql-server-dev-9.4
      before_script:
        - sudo make install
      script:
        - make installcheck
    - stage: test
      env: POSTGRESQL_VERSION=9.6
      before_script:
        - sudo make install
      script:
        - make installcheck
    - stage: test
      env: POSTGRESQL_VERSION=10; PGPORT=5433
      addons:
        postgresql: "10"
        apt:
          packages:
            - postgresql-server-dev-10
            - postgresql-10
            - postgresql-client-10
      before_script:
        - sudo make install
      script:
        - make installcheck

